######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 3 10:00:55 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += /usr/include/qt4/QtWebKit
LIBS += -lQtWebKit

# Input
HEADERS += browser.h
SOURCES += main.cpp
