######################################################################
# Automatically generated by qmake (2.01a) Tue Dec 14 17:50:34 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h posix_qextserialport.h qextserialbase.h
SOURCES += main.cpp mainwindow.cpp posix_qextserialport.cpp qextserialbase.cpp
